"""Add item_triggers to Scene model

Revision ID: a9b48e85a532
Revises: b0c8e66a5b44
Create Date: 2025-07-23 23:00:45.554593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9b48e85a532'
down_revision = 'b0c8e66a5b44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scenes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_triggers', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scenes', schema=None) as batch_op:
        batch_op.drop_column('item_triggers')

    # ### end Alembic commands ###
