"""Add item_triggers column to scenes

Revision ID: dbb887f74019
Revises: de79eb7ff75d
Create Date: 2025-07-28 16:52:55.367490

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dbb887f74019'
down_revision = 'de79eb7ff75d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scenes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_triggers', sa.JSON(), nullable=True))
        batch_op.alter_column('stage',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scenes', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('stage',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('item_triggers')

    # ### end Alembic commands ###
